server.port=8087

spring.application.name=notification-service
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=abms_db_notification;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa1}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
notification.dispatch-delay-ms=60000
