services:
  postgres:
    image: postgres:15
    container_name: abms-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: abms_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    networks:
      - abms-network

networks:
  abms-network:
    driver: bridge