server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
        - id: auth-service-users
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/users/**
        - id: apartment-service-buildings
          uri: ${APARTMENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/buildings/**
        - id: apartment-service
          uri: ${APARTMENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/apartments/**
        - id: vehicle-service
          uri: ${VEHICLE_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/vehicles/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/notifications/**
        - id: report-service
          uri: ${REPORT_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/reports/**

jwt:
  secret: ${JWT_SECRET:DayLaChuoiSecretKeyCuaDuAnABMSCanPhaiDaiHon256Bits}
