server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

jwt:
  secret: DayLaChuoiSecretKeyCuaDuAnABMSCanPhaiDaiHon256Bits

services:
  apartment-service:
    url: http://localhost:8082