server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/abms_db
    username: admin
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

jwt:
  secret: DayLaChuoiSecretKeyCuaDuAnABMSCanPhaiDaiHon256Bits

services:
  apartment-service:
    url: http://localhost:8082