server:
  port: 8083

spring:
  application:
    name: vehicle-service
  datasource:
    url: jdbc:postgresql://localhost:5435/vehicle_db
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

services:
  apartment-service:
    url: http://localhost:8082